### ISSUE TITLE
False positive with function pointer argument

### ISSUE THREAD

**Issue by damorinCan** [nimble-code/Uno#5]
Hi,

when the function argument have the same name as another variable, UNO is reporting an uninitialized variable.

``` c
int main( int argc, char **argv ) {
  int c;
  void (*pFct)( int c );

  c  = 1;
  if ( argc == 1 ) {
    pFct = This;
  } else {
    pFct = That;
  }
  *pFtc( 1 );
  return 0;
}
```

$ uno test.c
uno: ./test.c:3: in fct main, uninitialized variable 'c'
     statement  : ./test.c:3: void (*pFct)(int c);
     declaration: ./test.c:2: int c;
uno:    check completed, try 'uno -h' for different checks

Minor annoyance, just renaming to 'void (*pFct)( int d );' is solving the issue.

**Comment by nimble-code** [comment]
interesting case!
